spring:
  datasource:
    url: jdbc:mysql://localhost:8686/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: test
    password: test


knife4j:
  basic:
    enable: true
    username: test
    password: tset